# Generated by Django 4.2.6 on 2023-10-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0004_tabletype_remove_group_day_remove_group_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=5, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('is_activ', models.BooleanField(default=False)),
                ('descriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configApp.group')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configApp.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configApp.student')),
            ],
        ),
    ]
