# Generated by Django 4.2.6 on 2023-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configApp', '0005_level_levelnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
